#####
#  GitHub Pages / Jekyll settings / config

headers:
  title:     reveal.js
  subtitle:  The HTML Presentation Framework
  author:    Hakim El Hattab
  generator: GitHub Pages w/ Jekyll
  theme:     black


collections:
  slides:
    output: false


exclude:
- README.md
- BUILD.md
- CHANGELOG.md
- LICENSE.reveal.js.txt
- reveal.js.txt
- sample.md
